name: lifeos_frontend
description: "A new Flutter project."
publish_to: "none" # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.1.0 # <-- Added for storing tokens locally

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/robot.png
    - assets/robot2.png
    - assets/Robot3.png
